### ISSUE TITLE
Puppeteer: Failed to launch chrome

### ISSUE THREAD

**Issue by amra** [amra/DocumentationAsCode#5]
## Command
`docker run -w /foo -v `pwd`:/foo amra/documentation-as-code:mermaid pandoc -F mermaid-filter -o mermaid-test.html mermaid-test`

## Log
```
(node:17) UnhandledPromiseRejectionWarning: Error: Failed to launch chrome!
[0524/195314.254721:FATAL:zygote_host_impl_linux.cc(126)] No usable sandbox! Update your kernel or see https://chromium.googlesource.com/chromium/src/+/master/docs/linux_suid_sandbox_development.md for more information on developing with the SUID sandbox. If you want to live dangerously and need an immediate workaround, you can try using --no-sandbox.
#0 0x55773524f82c base::debug::StackTrace::StackTrace()
#1 0x5577351d6290 logging::LogMessage::~LogMessage()
#2 0x5577341cc5d1 content::ZygoteHostImpl::Init()
#3 0x557734f05d91 content::ContentMainRunnerImpl::Initialize()
#4 0x557734f0fc12 service_manager::Main()
#5 0x557734f04184 content::ContentMain()
#6 0x5577390dca39 headless::(anonymous namespace)::RunContentMain()
#7 0x5577390dcac2 headless::HeadlessBrowserMain()
#8 0x557734f0cf8f headless::HeadlessShellMain()
#9 0x5577334851ac ChromeMain
#10 0x7fa3629f2b45 __libc_start_main
#11 0x55773348502a _start

Received signal 6
#0 0x55773524f82c base::debug::StackTrace::StackTrace()
#1 0x55773524f391 base::debug::(anonymous namespace)::StackDumpSignalHandler()
#2 0x7fa36886d890 <unknown>
#3 0x7fa362a06067 gsignal
#4 0x7fa362a07448 abort
#5 0x55773524e1e5 base::debug::BreakDebugger()
#6 0x5577351d66da logging::LogMessage::~LogMessage()
#7 0x5577341cc5d1 content::ZygoteHostImpl::Init()
#8 0x557734f05d91 content::ContentMainRunnerImpl::Initialize()
#9 0x557734f0fc12 service_manager::Main()
#10 0x557734f04184 content::ContentMain()
#11 0x5577390dca39 headless::(anonymous namespace)::RunContentMain()
#12 0x5577390dcac2 headless::HeadlessBrowserMain()
#13 0x557734f0cf8f headless::HeadlessShellMain()
#14 0x5577334851ac ChromeMain
#15 0x7fa3629f2b45 __libc_start_main
#16 0x55773348502a _start
  r8: 00007fa368c6f9c0  r9: 0000046575a73800 r10: 0000000000000008 r11: 0000000000000206
 r12: 00007ffe40385ab8 r13: 0000000000000161 r14: 00007ffe40385ac0 r15: 00007ffe40385659
  di: 000000000000001b  si: 000000000000001b  bp: 00007ffe40385600  bx: 00007ffe40385670
  dx: 0000000000000006  ax: 0000000000000000  cx: 00007fa362a06067  sp: 00007ffe403854c8
  ip: 00007fa362a06067 efl: 0000000000000206 cgf: 002b000000000033 erf: 0000000000000000
 trp: 0000000000000000 msk: 0000000000000000 cr2: 0000000000000000
[end of stack trace]
Calling _exit(1). Core file will not be generated.


TROUBLESHOOTING: https://github.com/GoogleChrome/puppeteer/blob/master/docs/troubleshooting.md

    at onClose (/usr/local/lib/node_modules/mermaid-filter/node_modules/puppeteer/lib/Launcher.js:255:14)
    at Interface.helper.addEventListener (/usr/local/lib/node_modules/mermaid-filter/node_modules/puppeteer/lib/Launcher.js:244:50)
    at emitNone (events.js:111:20)
    at Interface.emit (events.js:208:7)
    at Interface.close (readline.js:368:8)
    at Socket.onend (readline.js:147:10)
    at emitNone (events.js:111:20)
    at Socket.emit (events.js:208:7)
    at endReadableNT (_stream_readable.js:1064:12)
    at _combinedTickCallback (internal/process/next_tick.js:138:11)
(node:17) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 1)
(node:17) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
fs.js:646
  return binding.open(pathModule._makeLong(path), stringToFlags(flags), mode);
                 ^

Error: ENOENT: no such file or directory, open '/tmp/tmp-10xRu7uNFc6wns.tmp.png'
    at Object.fs.openSync (fs.js:646:18)
    at Object.fs.readFileSync (fs.js:551:33)
    at mermaid (/usr/local/lib/node_modules/mermaid-filter/index.js:68:27)
    at /usr/local/lib/node_modules/mermaid-filter/node_modules/pandoc-filter/index.js:52:19
    at Array.forEach (<anonymous>)
    at walk (/usr/local/lib/node_modules/mermaid-filter/node_modules/pandoc-filter/index.js:50:7)
    at /usr/local/lib/node_modules/mermaid-filter/node_modules/pandoc-filter/index.js:74:16
    at Array.forEach (<anonymous>)
    at walk (/usr/local/lib/node_modules/mermaid-filter/node_modules/pandoc-filter/index.js:73:20)
    at filter (/usr/local/lib/node_modules/mermaid-filter/node_modules/pandoc-filter/index.js:36:10)
Error running filter mermaid-filter:
Filter returned error status 1
```

**Comment by amra** [comment]
Related to https://github.com/Googlechrome/puppeteer/issues/290
